// Auto-generated index file for Azure Functions v4
// This file imports all function handlers to register them with the runtime

import './ai-categorize'
import './anomalies'
import './approval-sla-check'
import './approvals'
import './attachments'
import './budget'
import './dashboard'
import './documents'
import './exchange-rates'
import './forecast'
import './vat'
import './health'
import './health-detailed'
import './invoice-document'
import './invoices'
import './ksef-invoices'
import './ksef-session'
import './ksef-status'
import './ksef-sync'
import './ksef-testdata'
import './manual-invoice'
import './notes'
import './notifications'
import './reports'
import './sessions'
import './settings-test-token'
import './settings'
import './sync'
import './mpk-centers'
import './users'
